FROM centos:latest

WORKDIR /src

RUN yum update -y
RUN yum install -y curl
RUN curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
RUN yum install -y nodejs
RUN npm install -g gulp
RUN yum install -y git

EXPOSE 8080 35729

CMD ["npm", "run", "serve"]
